[tools]
"swiftformat" = "0.55.3"
"spm:cpisciotta/xcbeautify" = "2.11.0"
"gh" = "2.58.0"
"git-cliff" = "2.6.1"

[settings]
yes = true
experimental = true
exec_auto_install = false
status.missing_tools = "never"
