name: Setup Environment
description: Sets up the environment for the workflow
inputs:
  swift-version:
    description: 'The version of Swift to use'
    required: true
  mise-version:
    description: 'The version of Mise to use'
    required: true
runs:
  using: "composite"
  steps:
    - name: Setup Mise
      uses: jdx/mise-action@v2
      with:
        version: ${{ inputs.mise-version }}
        install: false
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ inputs.swift-version }}
    - name: Setup Sake
      id: setup-sake
      uses: kattouf/setup-sake@v1
