name: Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  MISE_VERSION: 2024.12.21
jobs:
  build-and-test:
    name: tests (Swift ${{ matrix.swift }}) on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["6.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          mise-version: ${{ env.MISE_VERSION }}
          swift-version: ${{ matrix.swift }}
      - name: Build tests
        run: sake build_tests
      - name: Run unit tests
        run: sake unit_tests --skip-build
      - name: Run integration tests
        run: sake integration_tests --skip-build
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Environment
        uses: ./.github/actions/setup-environment
        with:
          mise-version: ${{ env.MISE_VERSION }}
          swift-version: 6.0
      - name: Run lint
        run: |
          sake lint
