name: Checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build-and-test:
    name: tests (Swift ${{ matrix.swift }}) on ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        swift: ["5.10", "6.0"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Sake
        uses: kattouf/sake-action@main
        with:
          swift-version: ${{ matrix.swift }}
      - name: Run unit tests
        run: sake unit_tests
      - name: Run integration tests
        run: sake integration_tests
  lint:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Sake
        uses: kattouf/sake-action@main
        with:
          swift-version: ${{ matrix.swift }}
      - name: Run lint
        run: |
          sake lint
