name: Tests
on: [push]
jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "5.10"
    - name: Build
      run: swift build
    - name: Run unit tests
      run: swift test --filter "^(?!.*\bIntegrationTests\b).*"
    - name: Run integration tests
      run: swift test --filter IntegrationTests
